export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";

export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";

export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL";

export const SAVE_SHIPPING_INFO_REQUEST = "SAVE_SHIPPING_INFO_REQUEST";

export const SAVE_SHIPPING_INFO_SUCCESS = "SAVE_SHIPPING_INFO_SUCCESS";

export const SAVE_SHIPPING_INFO_FAIL = "SAVE_SHIPPING_INFO_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
